<?php

namespace App\Api\V1\Controllers;

use App\Models\ReferralCode;
use App\Models\Total;
use App\Models\User;
use Illuminate\Http\Request;
use Throwable;

/**
 * Referral code Controller
 *
 * @package App\Api\V1\Controllers
 */
class SummaryController extends Controller
{
    /**
     * Get referral and codes summary
     *
     * @OA\Get(
     *     path="/summary",
     *     description="Get referral programm summary",
     *     tags={"Summary"},
     *
     *     security={{
     *         "default": {
     *             "ManagerRead",
     *             "User",
     *             "ManagerWrite"
     *         }
     *     }},
     *
     *     @OA\Response(
     *         response="200",
     *         description="TOP 1000 of leaders in the invitation referrals",
     *
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="object",
     *                 @OA\Property(
     *                     property="totalReferrals",
     *                     type="integer",
     *                     description="Total referrals by user",
     *                     example=10,
     *                 ),
     *                 @OA\Property(
     *                     property="totalCodesGenerated",
     *                     type="integer",
     *                     description="Total codes generated by user",
     *                     example=10,
     *                 ),
     *                 @OA\Property(
     *                     property="topReferralBonus",
     *                     type="integer",
     *                     description="Top referral bonus",
     *                     example=645000,
     *                 ),
     *                 @OA\Property(
     *                      property="amountEarned",
     *                      type="integer",
     *                      description="Amount earned by user",
     *                      example=450000,
     *                 ),
     *             ),
     *         ),
     *     ),
     *     @OA\Response(
     *         response="401",
     *         description="Unauthorized"
     *     ),
     *     @OA\Response(
     *         response=400,
     *         description="Invalid request"
     *     ),
     *     @OA\Response(
     *         response="404",
     *         description="User not found",
     *     ),
     *     @OA\Response(
     *         response="500",
     *         description="Unknown error"
     *     )
     * )
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return mixed
     */
    public function index(Request $request): mixed
    {
        try {

            $referrerId = Auth()->user()->getAuthIdentifier();

            $totalReferrals = User::where('referrer_id', $referrerId)->count();
            $totalCodesGenerated = ReferralCode::where('user_id', $referrerId)->count();
            $topReferralBonus = $this->getTopReferralBonus();
            $amountEarned = Total::where('user_id', $referrerId)->sum('reward');

            return response()->jsonApi([
                'type' => 'success',
                'title' => "List referral and codes summary",
                'message' => 'Referral and codes summary successfully received',
                'data' => [
                    'totalReferrals' => $totalReferrals,
                    'totalCodesGenerated' => $totalCodesGenerated,
                    'topReferralBonus' => $topReferralBonus,
                    'amountEarned' => $amountEarned,
                ],
            ], 200);
        } catch (Throwable $e) {
            return response()->jsonApi([
                'type' => 'danger',
                'title' => "Not received list",
                'message' => $e->getMessage(),
            ], 404);
        }
    }

    /**
     * @return mixed
     */
    protected function getTopReferralBonus(): mixed
    {
        $users = Total::distinct('user_id')->get('user_id');
        $topReferralBonus = $users->map(function ($user) {
            $userId = $user->user_id;
            $total = Total::where('user_id', $userId)->sum('reward');
            return [
                'total' => $total,
            ];
        })->sortByDesc('total')->first();
        return $topReferralBonus['total'];
    }
}
