<?php

namespace App\Api\V1\Controllers\Application;

use App\Api\V1\Controllers\Controller;
use App\Models\ReferralCode;
use App\Models\Total;
use App\Models\User;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Throwable;

/**
 * Referral code Controller
 *
 * @package App\Api\V1\Controllers\Application
 */
class SummaryController extends Controller
{
    /**
     * Get referral and codes summary
     *
     * @OA\Get(
     *     path="/summary",
     *     description="Get referral programm summary",
     *     tags={"Summary"},
     *
     *     security={{
     *         "default": {
     *             "ManagerRead",
     *             "User",
     *             "ManagerWrite"
     *         }
     *     }},
     *
     *     @OA\Response(
     *         response="200",
     *         description="TOP 1000 of leaders in the invitation referrals",
     *
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="object",
     *                 @OA\Property(
     *                     property="totalReferrals",
     *                     type="integer",
     *                     description="Total referrals by user",
     *                     example=10,
     *                 ),
     *                 @OA\Property(
     *                     property="totalCodesGenerated",
     *                     type="integer",
     *                     description="Total codes generated by user",
     *                     example=10,
     *                 ),
     *                 @OA\Property(
     *                     property="topReferralBonus",
     *                     type="integer",
     *                     description="Top referral bonus",
     *                     example=645000,
     *                 ),
     *                 @OA\Property(
     *                      property="amountEarned",
     *                      type="integer",
     *                      description="Amount earned by user",
     *                      example=450000,
     *                 )
     *             )
     *         )
     *     ),
     *     @OA\Response(
     *         response="401",
     *         description="Unauthorized"
     *     ),
     *     @OA\Response(
     *         response="400",
     *         description="Invalid request"
     *     ),
     *     @OA\Response(
     *         response="404",
     *         description="User not found",
     *     ),
     *     @OA\Response(
     *         response="500",
     *         description="Unknown error"
     *     )
     * )
     *
     * @param Request $request
     *
     * @return mixed
     */
    public function index(Request $request): mixed
    {
        try {
            $referrerId = Auth()->user()->getAuthIdentifier();

            $user = User::findOrFail($referrerId);

            $id = $user->id;
            $name = $user->name;
            $country = $user->country;

            $summary =  [
                    'id' => $id,
                    'name' => $name,
                    'country' => $country,
                    'totalReferrals' => User::query()->where('referrer_id', $referrerId)->count(),
                    'totalCodesGenerated' => ReferralCode::query()->where('user_id', $referrerId)->count(),
                    'amountEarned' => Total::query()->where('user_id', $referrerId)->sum('reward'),
                    'topReferralBonus' => Total::query()->max('reward'),
                    'rank' => 0,
                ];

            if (empty($summary)) {
                $summary = [
                    'id' => $id,
                    'name' => $name,
                    'country' => $country,
                    'totalReferrals' => 0,
                    'totalCodesGenerated' => 0,
                    'amountEarned' => 0,
                    'topReferralBonus' => 0,
                    'rank' => 0,
                ];
            }
            return response()->jsonApi([
                'title' => "List referral and codes summary",
                'message' => 'Referral and codes summary successfully received',
                'data' => $summary,
            ]);
        } catch (ModelNotFoundException $e) {
                $summary = [
                    'id' => "",
                    'name' => "",
                    'country' => "",
                    'totalReferrals' => 0,
                    'totalCodesGenerated' => 0,
                    'amountEarned' => 0,
                    'topReferralBonus' => 0,
                    'rank' => 0,
                ];
                return response()->jsonApi([
                    'title' => "List referral and codes summary",
                    'message' => 'User does not exist',
                    'data' => $summary,
                ], 404);
        } catch (Throwable $e) {
            return response()->jsonApi([
                'title' => "Not received list",
                'message' => $e->getMessage(),
            ], 404);
        }
    }

    /**
     * @return mixed
     */
    protected function getTopReferralBonus(): mixed
    {
        $users = Total::distinct('user_id')->get('user_id');

        $topReferralBonus = $users->map(function ($user) {
            $userId = $user->user_id;
            $total = Total::where('user_id', $userId)->sum('reward');

            return [
                'total' => $total,
            ];
        })->sortByDesc('total')->first();

        return $topReferralBonus['total'];
    }
}
